---
title: "Gamete Abundance Analysis"
author: "daniellembecker"
date: "2024-03-31"
output: html_document
---

This script will analyze gamete abundance in Acropora pulchra over time. The data is separated into timepointly timepoints and spermatogenesis and oogenesis.

## Load packages 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("gridExtra")
```

## Load data & select specific columns 
```{r}
#load data files
abundance <- read.csv("histology/data/histological_data.csv", header = T, na.strings = c("", "NA"))

# organize data make timepoints factors with levels in order for plots and calculate frequency
df_relative_abundance <- abundance %>%
  count(colony_id, replicate_id, site, timepoint, Stage, gonad.type, name = "stage_count") %>%
  group_by(colony_id, replicate_id, site, timepoint, gonad.type) %>%
  mutate(grand_tots = sum(stage_count)) %>%
  mutate(freq = stage_count / grand_tots)

# change the freq to 0 whenever the corresponding Stage column has NA
df_relative_abundance <- df_relative_abundance %>%
  mutate(freq = ifelse(is.na(Stage), 0, freq),
    grand_tots = ifelse(is.na(Stage), 0, grand_tots),
    stage_count = ifelse(is.na(Stage), 0, stage_count))

# creates a new column in the df_relative_abundance dataframe called group, which is a combination of the timepoint and colony_id columns
df_relative_abundance$group <- paste0(df_relative_abundance$timepoint,"_", df_relative_abundance$colony_id)

# convert the Stage column in the df_relative_abundance dataframe to a factor with specified levels
df_relative_abundance$Stage <- factor(df_relative_abundance$Stage, levels = c("StageI","StageII","StageIII","StageIV", "StageV"))

```

Oogenesis
```{r}
# select just oocytes, remove any spermatocyte data
oogen_df_relative_abundance <- df_relative_abundance %>%
  filter(gonad.type != "spermatocyte")

# Reorder the levels of the 'timepoint' variable from December to October
oogen_df_relative_abundance$timepoint <- factor(oogen_df_relative_abundance$timepoint, 
                                                 levels = c("December", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October"),
                                                 ordered = TRUE)


# Plot with reordered months and unique grand_tots on x-axis
oogen <- oogen_df_relative_abundance %>% 
  ggplot(aes(x = replicate_id, y = freq, fill = Stage)) +
  geom_col() +
  facet_wrap(~ timepoint, ncol = 11) +
  theme_bw() +
  ylab("Proportion of Oocytes") +
  xlab("Colony ID") +
  theme(axis.text.x = element_text(angle = 90),
        legend.position = "top",  # Move legend to top
        legend.title = element_blank()) +  
  scale_y_continuous(expand = c(0, 0))  + # Ensure the y-axis starts at 0
  guides(color = guide_legend(ncol = length(unique(oogen_df_relative_abundance$Stage)), byrow = TRUE), 
         fill = guide_legend(ncol = length(unique(oogen_df_relative_abundance$Stage)), byrow = TRUE))  # Set ncol and byrow for the legend # Remove legend titles

oogen


```

Spermatogenesis
```{r}
spermato_df_relative_abundance <- df_relative_abundance %>%
  filter(!gonad.type=="oocyte")

spermato <- spermato_df_relative_abundance %>% ggplot(aes(x=colony_id, y=freq, group=stage, color=stage, fill=stage)) +
  geom_col()+
  #geom_text(aes(label=grand.tots),color="black", size=1.5, vjust = 0.1)+
  facet_wrap(c("site", "timepoint"), ncol=11)+
  theme_bw()+
  ylab("Proportion of Sperm")+
  theme(axis.text.x = element_text(angle = 90))

spermato
```



Arrange and save plots
```{r}

plots <- grid.arrange(oogen, spermato, nrow = 2)

ggsave("histology/output/Gametogenesis.pdf", plots , width = 10, height = 6)
ggsave("histology/output/Gametogenesis.jpg", plots , width = 10, height = 6)


```
